from sqlalchemy import create_engine, Column, Integer, String, Float, Text, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from datetime import datetime
import sqlite3

DATABASE_URL = "sqlite:///./chronicle.db"
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    password_hash = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)


class PageCapture(Base):
    __tablename__ = "captures"

    id = Column(Integer, primary_key=True, index=True)
    url = Column(String, index=True)
    title = Column(String)
    domain = Column(String, index=True)
    timestamp = Column(Float, index=True)       # unix ms
    visit_start = Column(Float)
    duration_seconds = Column(Float, default=0)
    selected_text = Column(Text, nullable=True)
    page_text = Column(Text, nullable=True)
    tab_id = Column(Integer)
    session_id = Column(String, index=True)
    cluster_id = Column(Integer, nullable=True, index=True)
    cluster_label = Column(String, nullable=True)
    embedded = Column(Integer, default=0)       # 0 = not yet embedded
    created_at = Column(DateTime, default=datetime.utcnow)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

class BrowsingSession(Base):
    """Groups of related pages (auto-generated by clustering)"""
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    label = Column(String)              # e.g. "Learning CUDA optimization"
    summary = Column(Text, nullable=True)
    start_time = Column(Float)
    end_time = Column(Float)
    page_count = Column(Integer, default=0)
    cluster_id = Column(Integer, unique=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

def init_db():
    Base.metadata.create_all(bind=engine)
    
    # Simple manual migration for SQLite to add user_id to existing tables
    try:
        with sqlite3.connect("./chronicle.db") as conn:
            cursor = conn.cursor()
            # Check if user_id exists in captures
            cursor.execute("PRAGMA table_info(captures)")
            columns = [info[1] for info in cursor.fetchall()]
            if "user_id" not in columns:
                cursor.execute("ALTER TABLE captures ADD COLUMN user_id INTEGER REFERENCES users(id)")
            
            # Check if user_id exists in sessions
            cursor.execute("PRAGMA table_info(sessions)")
            columns = [info[1] for info in cursor.fetchall()]
            if "user_id" not in columns:
                cursor.execute("ALTER TABLE sessions ADD COLUMN user_id INTEGER REFERENCES users(id)")
            conn.commit()
    except Exception as e:
        print("Migration error:", e)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()