from sqlalchemy import create_engine, Column, Integer, String, Float, Text, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime

DATABASE_URL = "sqlite:///./chronicle.db"
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class PageCapture(Base):
    __tablename__ = "captures"

    id = Column(Integer, primary_key=True, index=True)
    url = Column(String, index=True)
    title = Column(String)
    domain = Column(String, index=True)
    timestamp = Column(Float, index=True)       # unix ms
    visit_start = Column(Float)
    duration_seconds = Column(Float, default=0)
    selected_text = Column(Text, nullable=True)
    page_text = Column(Text, nullable=True)
    tab_id = Column(Integer)
    session_id = Column(String, index=True)
    cluster_id = Column(Integer, nullable=True, index=True)
    cluster_label = Column(String, nullable=True)
    embedded = Column(Integer, default=0)       # 0 = not yet embedded
    created_at = Column(DateTime, default=datetime.utcnow)


class BrowsingSession(Base):
    """Groups of related pages (auto-generated by clustering)"""
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    label = Column(String)              # e.g. "Learning CUDA optimization"
    summary = Column(Text, nullable=True)
    start_time = Column(Float)
    end_time = Column(Float)
    page_count = Column(Integer, default=0)
    cluster_id = Column(Integer, unique=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)


def init_db():
    Base.metadata.create_all(bind=engine)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()